Check to validate stack tag values
Sceptre/sceptrelint pull request #6
Opened 2022-05-27 05:30 UTC by zaro0508

Add a hook to check that the assigned values
to stack tags are valid.

2022-06-02 21:01 UTC, brucehoff requested changes

2022-06-02 22:05 UTC, zaro0508 commented on README.md
> +    args: [--tag=CostCenter, --file=/path/to/file.json]
yes, i can document that.  I do prefer the shorter `--file` flag though.

2022-06-02 22:09 UTC, zaro0508 commented on tests/check_stack_tag_values_test.py
> +    files = [f'{resource_path}/stack_tags_match_tag_values2.yaml']
yes, the test is to verify that `green` is valid.  Are you just making a comment or pointing out something that's not correct?

2022-06-03 02:03 UTC, brucehoff commented on tests/check_stack_tag_values_test.py
> +    files = [f'{resource_path}/stack_tags_match_tag_values2.yaml']
I was just making a comment as I was trying to follow what the test was doing.

2022-06-03 18:42 UTC, zaro0508 commented on README.md
> +    args: [--tag=CostCenter, --file=/path/to/file.json]
done

2022-06-03 18:42 UTC, zaro0508 commented on README.md
> +__Note__: The `--file` flag can take a local or a url reference (i.e. https://raw.githubusercontent.com/acme/repo/master/tags/cost_center_codes.json). The `--file` flage can be use multiple times to
fixed

2022-06-03 21:38 UTC, brucehoff approved these changes

2022-06-03 21:40 UTC, brucehoff approved these changes

2022-06-03 23:03 UTC, merged